<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Home Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'Jocelyne.Marine@tampico.com',
		'to' => 'Jocelyne.Marine@tampico.com'
	),
	'fields' => array(
		'custom_U13806' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'NOMBRE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'NOMBRE\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'EMAIL',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'EMAIL\' is required.',
				'format' => 'Field \'EMAIL\' has an invalid email.'
			)
		),
		'custom_U13816' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'MENSAJE',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'MENSAJE\' is required.'
			)
		),
		'custom_U13801' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'DEPARTAMENTO',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'DEPARTAMENTO\' is required.'
			)
		),
		'custom_U13796' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'CIUDAD',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'CIUDAD\' is required.'
			)
		),
		'custom_U13811' => array(
			'order' => 6,
			'type' => 'checkbox',
			'label' => 'Acepto en su totalidad y me obligo a cumplir por completo con la Política de Privacidad y con las Condiciones de Uso de Tampico',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Acepto en su totalidad y me obligo a cumplir por completo con la Política de Privacidad y con las Condiciones de Uso de Tampico\' is required.'
			)
		)
	)
);

process_form($form);
?>
